FROM node:6.6

ARG ver

ENV PATH=/node_modules/.bin:$PATH NODE_PATH=$NODE_PATH:/node_modules SERVERLESS_VERSION=$ver

RUN npm install -g serverless@$ver

WORKDIR /

ADD package.json /package.json

RUN npm install

ADD . /service

WORKDIR /service
